#!/usr/bin/env bash

docker kill proxy

set -e

export AWS_BUCKET=7b33087a-5447-491a-8b82-cd2ec2f45153
export S3_CREDENTIAL_SCOPE=us-east-1
export AWS_CREDENTIALS=http4kbox:http4kbox

# Use docker to port forward
docker run --rm --detach --name proxy -e REMOTE_HOST=7b33087a-5447-491a-8b82-cd2ec2f45153.s3.amazonaws.com -e REMOTE_PORT=443 -p 8080:80 djfaze/port-forward

./native 5000